// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUuyIWQy1S0yX2elm5r8z5x0c9Q-jcQs',
    appId: '1:369569134416:web:b4be3af5a153172b381e55',
    messagingSenderId: '369569134416',
    projectId: 'chatting-app-1ce79',
    authDomain: 'chatting-app-1ce79.firebaseapp.com',
    storageBucket: 'chatting-app-1ce79.appspot.com',
    measurementId: 'G-1MBHKLS7GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGK3PU4jIaP4DP_IbfIXWRNssnUbO5VXM',
    appId: '1:369569134416:android:de0b0f0e27b5d5e7381e55',
    messagingSenderId: '369569134416',
    projectId: 'chatting-app-1ce79',
    storageBucket: 'chatting-app-1ce79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBik3j6SmC7Vpggpf4OzwMneHKx9F7Wbl4',
    appId: '1:369569134416:ios:8538d992a5fd4ad0381e55',
    messagingSenderId: '369569134416',
    projectId: 'chatting-app-1ce79',
    storageBucket: 'chatting-app-1ce79.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBik3j6SmC7Vpggpf4OzwMneHKx9F7Wbl4',
    appId: '1:369569134416:ios:8538d992a5fd4ad0381e55',
    messagingSenderId: '369569134416',
    projectId: 'chatting-app-1ce79',
    storageBucket: 'chatting-app-1ce79.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoUuyIWQy1S0yX2elm5r8z5x0c9Q-jcQs',
    appId: '1:369569134416:web:397a1c82b54bc404381e55',
    messagingSenderId: '369569134416',
    projectId: 'chatting-app-1ce79',
    authDomain: 'chatting-app-1ce79.firebaseapp.com',
    storageBucket: 'chatting-app-1ce79.appspot.com',
    measurementId: 'G-QBPTPMMJ04',
  );
}
